layout_spectrum: 0.5494092
color:
  saturation: 0.3356606
  brandStrength: 0.1573632
  lightness: 0.1573576
  rhythmicContrast: 0.4534717
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.9006445
name: Fixes
